version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6

    working_directory: ~/workspace
    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            wget https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_linux_386.zip
            unzip terraform_0.10.2_linux_386.zip
            sudo mv terraform /usr/local/bin/
            sudo chmod 777 /usr/local/bin/
            export PATH=$PATH:/usr/local/bin/
            source ~/.bashrc
            terraform -v
            echo "export PATH=$PATH:/usr/local/bin/" >> ~/.bash_profile
            pwd
            cd /home/circleci/workspace/.circleci
            echo "heelo"
            chmod u+x /home/circleci/workspace/.circleci/package_lambda.sh
            ./package_lambda.sh ~/workspace
            zip -r ~/ngp_automation_switchboard.zip /home/circleci/workspace/pipeline/ /home/circleci/workspace/lambda_functions /home/circleci/workspace/src
            cd /home/circleci/workspace/pipeline
            terraform init && terraform plan && terraform apply
