version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6

    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            wget https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_linux_386.zip
            unzip terraform_0.10.2_linux_386.zip
            sudo mv terraform /usr/local/bin/
            sudo chmod 777 /usr/local/bin/
            export PATH=$PATH:/usr/local/bin/
            source ~/.bashrc
            terraform -v
            echo "export PATH=$PATH:/usr/local/bin/" >> ~/.bash_profile
            cd ~/circ-code/.circleci/
            ./package_lambda.sh ~/workspace
            zip -r ./pipeline/lambda.zip ./switchboard.py
            pushd pipeline && terraform init && terraform plan && terraform apply && popd
